name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_upload:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build . --no-cache --file Dockerfile --tag vie-doors

    - name: Save Docker Image
      run: docker save vie-doors -o vie-doors.tar

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vie-doors
        path: vie-doors.tar
        retention-days: 1