name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Build image
      run: docker build . --no-cache --file Dockerfile --tag vie-doors

    - name: Store artifact in GitHub
      uses: actions/upload-artifact@v4
      with:
        name: vie-doors
        path: /var/lib/docker/vie-doors
        retention-days: 1