name: Docker Image Release

on:
  release:
    types: [created]

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Build image
      run: docker build . --file Dockerfile --tag vie-doors

    - name: Save Docker Image
      run: docker save vie-doors -o vie-doors.tar

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.VIEDOORS_GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: vie-doors.tar
        asset_name: vie-doors.tar
        asset_content_type: application/x-tar